version: '3.7'

services:
  crud:
    image: postgres 
    container_name: planetinhas
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=planetinhas
    volumes:
      - pgdata:/data/postgres/post


volumes:
  pgdata:
    driver: local
